import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

export async function POST() {
  try {
      const supabase = await createClient()
          const {
                data: { user },
                    } = await supabase.auth.getUser()

                        if (!user || !user.email) {
                              return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
                                  }

                                      const apiKey = process.env.ENRICHLAYER_API_KEY
                                          if (!apiKey) {
                                                return NextResponse.json({ error: "Missing ENRICHLAYER_API_KEY" }, { status: 500 })
                                                    }

                                                        /* -------------------------------------------------------
                                                               STEP 1 — Reverse email lookup → public_identifier
                                                                   ------------------------------------------------------- */

                                                                       const emailUrl = new URL("https://enrichlayer.com/api/v2/profile/resolve/email")
                                                                           emailUrl.searchParams.set("email", user.email)
                                                                               emailUrl.searchParams.set("lookup_depth", "deep")

                                                                                   const emailRes = await fetch(emailUrl.toString(), {
                                                                                         headers: { Authorization: `Bearer ${apiKey}` },
                                                                                             })

                                                                                                 if (!emailRes.ok) {
                                                                                                       return NextResponse.json(
                                                                                                               { error: "Email lookup failed", raw: await emailRes.text() },
                                                                                                                       { status: 502 },
                                                                                                                             )
                                                                                                                                 }

                                                                                                                                     const emailData = await emailRes.json()
                                                                                                                                         const publicIdentifier =
                                                                                                                                               emailData?.public_identifier ?? emailData?.profile?.public_identifier

                                                                                                                                                   if (!publicIdentifier) {
                                                                                                                                                         return NextResponse.json(
                                                                                                                                                                 { error: "No LinkedIn public_identifier resolved" },
                                                                                                                                                                         { status: 404 },
                                                                                                                                                                               )
                                                                                                                                                                                   }

                                                                                                                                                                                       /* -------------------------------------------------------
                                                                                                                                                                                              STEP 2 — Full profile fetch (NO METADATA MODE)
                                                                                                                                                                                                  ------------------------------------------------------- */

                                                                                                                                                                                                      const profileUrl = new URL("https://enrichlayer.com/api/v2/profile")
                                                                                                                                                                                                          profileUrl.searchParams.set("public_identifier", publicIdentifier)
                                                                                                                                                                                                              profileUrl.searchParams.set("skills", "include")
                                                                                                                                                                                                                  profileUrl.searchParams.set("experience", "include")
                                                                                                                                                                                                                      profileUrl.searchParams.set("education", "include")
                                                                                                                                                                                                                          profileUrl.searchParams.set("use_cache", "if-present")
                                                                                                                                                                                                                              profileUrl.searchParams.set("fallback_to_cache", "on-error")

                                                                                                                                                                                                                                  const profileRes = await fetch(profileUrl.toString(), {
                                                                                                                                                                                                                                        headers: { Authorization: `Bearer ${apiKey}` },
                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                if (!profileRes.ok) {
                                                                                                                                                                                                                                                      return NextResponse.json(
                                                                                                                                                                                                                                                              { error: "Profile fetch failed", raw: await profileRes.text() },
                                                                                                                                                                                                                                                                      { status: 502 },
                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    const profileData = await profileRes.json()

                                                                                                                                                                                                                                                                                        /* -------------------------------------------------------
                                                                                                                                                                                                                                                                                               HARD GUARDS — reject metadata / compatibility payloads
                                                                                                                                                                                                                                                                                                   ------------------------------------------------------- */

                                                                                                                                                                                                                                                                                                       if (
                                                                                                                                                                                                                                                                                                             !profileData ||
                                                                                                                                                                                                                                                                                                                   typeof profileData !== "object" ||
                                                                                                                                                                                                                                                                                                                         "backwards_compatibility_notes" in profileData ||
                                                                                                                                                                                                                                                                                                                               (!profileData.full_name && !profileData.experiences)
                                                                                                                                                                                                                                                                                                                                   ) {
                                                                                                                                                                                                                                                                                                                                         return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                 {
                                                                                                                                                                                                                                                                                                                                                           error: "Invalid EnrichLayer profile payload",
                                                                                                                                                                                                                                                                                                                                                                     raw: profileData,
                                                                                                                                                                                                                                                                                                                                                                             },
                                                                                                                                                                                                                                                                                                                                                                                     { status: 502 },
                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                   /* -------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                          STEP 3 — Sanitize (remove nulls only)
                                                                                                                                                                                                                                                                                                                                                                                                              ------------------------------------------------------- */

                                                                                                                                                                                                                                                                                                                                                                                                                  const sanitizedProfile = sanitizeProfile(profileData)

                                                                                                                                                                                                                                                                                                                                                                                                                      /* -------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                             STEP 4 — Persist
                                                                                                                                                                                                                                                                                                                                                                                                                                 ------------------------------------------------------- */

                                                                                                                                                                                                                                                                                                                                                                                                                                     const { error: upsertError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                           .from("people")
                                                                                                                                                                                                                                                                                                                                                                                                                                                 .upsert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                         {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   id: user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             email: user.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       resume_raw: profileData,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 resume_content: sanitizedProfile,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           resume_content_modified: sanitizedProfile,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     public_identifier: publicIdentifier,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               vanity_url: publicIdentifier,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         updated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { onConflict: "id" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (upsertError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 { error: "Failed to save profile" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 500 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   profile: sanitizedProfile,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   { error: err instanceof Error ? err.message : "Unknown error" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 500 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               function sanitizeProfile(data: Record<string, unknown>): Record<string, unknown> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const result: Record<string, unknown> = {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   for (const [key, value] of Object.entries(data)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (value === null) continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (Array.isArray(value)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 result[key] = value.map((v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         typeof v === "object" && v !== null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ? sanitizeProfile(v as Record<string, unknown>)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             : v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       } else if (typeof value === "object") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             result[key] = sanitizeProfile(value as Record<string, unknown>)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       result[key] = value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
