// TEMPORARY: Delete this file after testing
// This provides fallback mock data for testing the resume viewer UI

export const MOCK_PROFILE_DATA = {
  city: "Seattle",
  meta: { last_updated: "2025-07-10T00:00:00Z" },
  extra: null,
  state: "Washington",
  gender: null,
  groups: [],
  skills: [],
  country: "US",
  summary: "As a Sr Product Designer at Airtime, I have over 18 years of experience in creating engaging and delightful user experiences that solve complex and meaningful challenges. I have worked with leading companies such as Xbox, Meta, Microsoft, and Mythical Games, designing and launching products across various platforms and domains, including gaming, social media, e-commerce, and blockchain.\n\nAt Airtime, I lead the design of innovative and inclusive features that leverage ML and AI to enable non-toxic social interactions and asynchronous communication. I also build and champion design systems and processes that facilitate collaboration, feedback, and handoff between design and development teams. My mission is to fight for the user and the player, and to empower them with products that enrich their lives and connect them with others.",
  articles: [
    {
      link: "https://www.linkedin.com/pulse/looking-visual-effects-artist-video-game-drew-andersen",
      title: "Looking for Visual Effects Artist for Video Game",
      author: null,
      image_url: null,
      published_date: { day: 21, year: 2015, month: 5 },
    },
  ],
  headline: "Product Design Leader | ML | Xbox, Meta, Microsoft",
  industry: null,
  education: [],
  full_name: "Drew Andersen",
  interests: [],
  languages: [],
  last_name: "Andersen",
  activities: [
    {
      link: null,
      title: "20 days' holiday is not a benefit. Sorry, but it's true. We're well past anyone being impressed by your ability to comply with the law so it's a…",
      activity_status: null,
    },
    {
      link: null,
      title: "So, I'm working on a short film as a personal project to push myself, and also I just love story telling. I've been trying to level up my renders and…",
      activity_status: null,
    },
    {
      link: null,
      title: "Warface weapon reload animation #Warface #BlackwoodGames #3danimaion #WeaponAnimation #ReloadAnimation",
      activity_status: null,
    },
  ],
  birth_date: null,
  first_name: "Drew",
  occupation: "Sr Product Designer at Airtime",
  connections: 500,
  public_identifier: "drew-andersen-ux",
  experiences: [
    {
      title: "Sr Product Designer",
      company: "Airtime",
      ends_at: { day: 1, year: 2023, month: 5 },
      location: null,
      logo_url: null,
      starts_at: { day: 1, year: 2022, month: 5 },
      description: "Drive more Design, build and champion compelling and delightful user-experiences that drive non-toxic social into the new age of asynchronous communication.",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/airtime",
    },
    {
      title: "Lead UX/UI Designer",
      company: "Mythical Games",
      ends_at: { day: 1, year: 2022, month: 5 },
      location: "Greater Seattle Area",
      logo_url: null,
      starts_at: { day: 1, year: 2020, month: 8 },
      description: "- Build and lead a team full of industry-veteran, UX, UI, and Visual designers to create Blankos Block Party and many other product verticals.\n- Build the design infrastructure, design systems, and create a seamless bridge between design and dev that make design handoff effortless and elegant\n- Concept, wireframe, and design player-tested prototypes to cost for dev and gather feedback from UR studies for iterative releases\n- Work through highly complex and time sensitive challenges that solve both shorterm (MVP) business and player objectives, and scale painlessly for post MVP phasing\n- Launch the thing. Make people happy. And celebrate",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/mythical",
    },
    {
      title: "UI Artist III",
      company: "Turn 10 Studios",
      ends_at: { day: 1, year: 2020, month: 8 },
      location: "Redmond, Washington",
      logo_url: null,
      starts_at: { day: 1, year: 2019, month: 11 },
      description: "Responsibilities:\n- Designed screens and components to complete cross-functional tasks\n- Constructed detailed documentation and personal training around internal design infrastructures built for quick design through code objectives\n- Created a system used to accelerate the design to code handover process\n- Work often and closely with UX and UR on journey maps, focus groups, and meeting accessibility guidelines for PC and Console experiences\n- Worked closely with developers around prompts provided by technical art leads to ensure clean handovers for complex UI systems",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/turn-10-studios",
    },
    {
      title: "UX Designer",
      company: "Facebook",
      ends_at: { day: 1, year: 2019, month: 7 },
      location: "Seattle, Washington",
      logo_url: null,
      starts_at: { day: 1, year: 2019, month: 4 },
      description: "UI/UX Design for Facebook Marketplace on iOS and Android.\n- UX research, journey maps, user studies, user testing.\n- Worked closely with cross-functional teams to provide solutions for peer-to-peer shipping functionality in Marketplace.\n- Note that this was a short-term contract to help Fb fulfill this feature",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/facebook",
    },
    {
      title: "UI Designer II",
      company: "Xbox Game Studios Publishing",
      ends_at: { day: 1, year: 2019, month: 4 },
      location: "Redmond, Washington",
      logo_url: null,
      starts_at: { day: 1, year: 2018, month: 7 },
      description: "Building the experiences behind Mixer on the Xbox console and desktop experience.\nA major task included redesigning the Xbox app. This massive project presented multiple deep challenges, such as:\nConsole UX focused behavioral research, building for console based user expectation, Xbox controller flows, and player-centric research.\n\nGeneral tasks include:\nWireframing, rapid prototyping, e-commerce integrations, animations, micro-interactions, interactive design, design systems (ex. UI patterns), interactive media, co-op experiences, and intentional user delights.",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/xbox-publishing",
    },
    {
      title: "Lead UX Designer",
      company: "Overstock.com",
      ends_at: { day: 1, year: 2018, month: 7 },
      location: "Midvale, Utah",
      logo_url: null,
      starts_at: { day: 1, year: 2017, month: 9 },
      description: "Responsibilities:\n- Rebrand/redesign web and mobile application for Cars\n- UI/UX design for web and mobile applications\n- User testing\n- Creating the flow for UX architecture\n- Interactive design\n- Brand design/development\n- Building design systems and processes\n- Building and managing scalable UI patterns\n- Illustrations, animations, font iconography, and marketing design",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/overstock",
    },
    {
      title: "Sr. UX Designer",
      company: "MOJO Marketplace",
      ends_at: { day: 1, year: 2017, month: 9 },
      location: "Salt Lake City, Utah",
      logo_url: null,
      starts_at: { day: 1, year: 2017, month: 1 },
      description: "- Developed the MOJO design language and UI patterns\n- Took the 'marketplace' and integrated it into 32 other hosting products.\nThis process required redesigning multiple partner's (Bluehost, Host Gator) back-end user admin system and front-end cPanel -- to incorporate seamless transaction between both products. Other reqs to accomplish\nthis were:\n- UI/UX design for mobile and web apps\n- GSAP and Principle interactions\n- User testing\n- Brand direction\n- Pair-design/programming sessions\n- Marketing strategy",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/mojo-marketplace",
    },
    {
      title: "Sr UX designer",
      company: "diib",
      ends_at: { day: 1, year: 2014, month: 12 },
      location: "Greater Salt Lake City Area",
      logo_url: null,
      starts_at: { day: 1, year: 2014, month: 1 },
      description: "Lead UX Designer\n- UI/UX design for web and mobile applications\n- User testing and focus groups\n- Journey maps, personas, UI Patterns, and A/B testing\n- Interactive design\n- Building and managing scalable UI patterns\n- Illustrations, animations, iconography",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: "https://www.linkedin.com/company/diib",
    },
    {
      title: "Career Break",
      company: "",
      ends_at: { day: 1, year: 2023, month: 9 },
      location: null,
      logo_url: null,
      starts_at: { day: 1, year: 2023, month: 5 },
      description: "Several months of non-stop, intensive dedication around implementing, tuning, and advancing Machine-Learning models for artificial-intelligence",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: null,
    },
    {
      title: "Product & Brand Designer",
      company: "StickyPig - Full Time Freelance",
      ends_at: { day: 1, year: 2017, month: 9 },
      location: "Greater Salt Lake City Area",
      logo_url: null,
      starts_at: { day: 1, year: 2013, month: 1 },
      description: "UX / UI design, mobile app design, web design, UX flows, personas, UX research",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: null,
    },
    {
      title: "Design Director",
      company: "Wooly",
      ends_at: { day: 1, year: 2016, month: 2 },
      location: "Greater Salt Lake City Area",
      logo_url: null,
      starts_at: { day: 1, year: 2014, month: 1 },
      description: "Responsibilities:\n- create wireframes, chart flows, UI patterns, create design\nsystems\n- Implement user-driven features using HotJar, Mouseflow, and\nfocus surveys\n- Social data visualization, connect clients to influencers\n- develop visual identity for brand and UI",
      company_facebook_profile_url: null,
      company_linkedin_profile_url: null,
    },
    {
      title: "Art Director",
      company: "CompuSoft Development",
      ends_at: { day: 1, year: 2013, month: 2 },
      location: "Greater Salt Lake City Area",
      logo_url: null,
      starts_at: { day: 1, year: 2007, month: 2 },
      description: null,
      company_facebook_profile_url: null,
      company_linkedin_profile_url: null,
    },
  ],
}

export const MOCK_THEME_DATA = {
  name: "Modern",
  fonts: {
    body: "Inter, sans-serif",
    heading: "Inter, sans-serif",
  },
  colors: {
    text: "#1f2937",
    accent: "#3b82f6",
    primary: "#2563eb",
    secondary: "#e2e8f0",
    background: "#ffffff",
  },
  layout: {
    spacing: "1.5rem",
    borderRadius: "0.5rem",
  },
}

// Set to true to use mock data instead of fetching from Supabase/API
export const USE_MOCK_DATA = true
